# preprocess settings
preprocess:
    resampling: False
    resampling_type: over
    resampling_seed: 71
    os_lim: 10000

# training settings
train:
    debug: True
    mode: reg
    fold_num: 5
    rm_outliers: False
    fold_type: skf
    single_model: False
    all_features: False
    feature_selection: False
    feature_select_path: 'importances/'
    metric: 'split_cov'
    feature_topk: 150

# lightGBM parameters
lgbm_params:
    boosting: gbdt
    verbose: -1
    random_state: 71
    objective: binary
    metric: auc
    learning_rate: 0.05
    num_leaves: 31
    max_depth: -1
    subsample: 0.8
    bagging_freq: 1
    colsample_bytree: 0.8
    min_data_in_leaf: 30
    lambda_l1: 0.1
    min_data_per_group: 1
    cat_smooth: 1
    cat_l2: 0
    max_cat_to_onehot: 10
    #    min_split_gain: 
    #    min_child_weight: 
    #    max_bin: 

# features
features: 
    - MachineIdentifier
    - le_AppVersion
    - le_Census_ChassisTypeName

categorical_features:
    - le_AppVersion
    - le_Census_ChassisTypeName

invalid_features:
    #    - # HasDetections
