# preprocess settings
preprocess:
    resampling: False
    resampling_type: over
    resampling_seed: 71
    os_lim: 10000

# training settings
train:
    debug: False
    fold_num: 5
    rm_outliers: False
    fold_type: tssf
    #    single_model: True
    all_features: False
    feature_selection: False
    feature_select_path: 'importances/'
    metric: 'split_cov'
    feature_topk: 150

# lightGBM parameters
lgbm_params:
    boosting: gbdt
    verbose: -1
    random_state: 71
    objective: binary
    metric: auc
    learning_rate: 0.1
    num_leaves: 63
    max_depth: -1
    subsample: 0.8
    bagging_freq: 1
    colsample_bytree: 0.5
    min_data_in_leaf: 60
    lambda_l1: 0.1
    min_data_per_group: 1
    cat_smooth: 750
    cat_l2: 100
    max_cat_to_onehot: 10
    #    min_split_gain: 
    #    min_child_weight: 
    #    max_bin: 

# features
features: 
    - MachineIdentifier
    - AVProductsInstalled
    - Census_InternalBatteryNumberOfCharges
    - Census_InternalPrimaryDiagonalDisplaySizeInInches
    - Census_InternalPrimaryDisplayResolutionHorizontal
    - Census_InternalPrimaryDisplayResolutionVertical
    - Census_PrimaryDiskTotalCapacity
    - Census_ProcessorCoreCount
    - Census_SystemVolumeTotalCapacity
    - Census_TotalPhysicalRAM
    - cce_le_AppVersion
    - cce_le_AutoSampleOptIn
    - cce_le_AVProductsEnabled
    - cce_le_AVProductStatesIdentifier
      #    - cce_le_AvSigVersion
    - cce_le_Census_ActivationChannel
    - cce_le_Census_ChassisTypeName
    - cce_le_Census_DeviceFamily
    - cce_le_Census_FirmwareManufacturerIdentifier
      #    - cce_le_Census_FirmwareVersionIdentifier
    - cce_le_Census_FlightRing
    - cce_le_Census_GenuineStateName
    - cce_le_Census_HasOpticalDiskDrive
    - cce_le_Census_InternalBatteryType
    - cce_le_Census_IsAlwaysOnAlwaysConnectedCapable
    - cce_le_Census_IsFlightingInternal
    - cce_le_Census_IsFlightsDisabled
    - cce_le_Census_IsPenCapable
    - cce_le_Census_IsPortableOperatingSystem
    - cce_le_Census_IsSecureBootEnabled
    - cce_le_Census_IsTouchEnabled
    - cce_le_Census_IsVirtualDevice
    - cce_le_Census_IsWIMBootEnabled
    - cce_le_Census_MDC2FormFactor
      #    - cce_le_Census_OEMModelIdentifier
      #    - cce_le_Census_OEMNameIdentifier
    - cce_le_Census_OSArchitecture
    - cce_le_Census_OSBranch
    - cce_le_Census_OSBuildNumber
    - cce_le_Census_OSBuildRevision
    - cce_le_Census_OSEdition
    - cce_le_Census_OSInstallLanguageIdentifier
    - cce_le_Census_OSInstallTypeName
    - cce_le_Census_OSSkuName
    - cce_le_Census_OSUILocaleIdentifier
    - cce_le_Census_OSVersion
    - cce_le_Census_OSWUAutoUpdateOptionsName
    - cce_le_Census_PowerPlatformRoleName
    - cce_le_Census_PrimaryDiskTypeName
    - cce_le_Census_ProcessorClass
    - cce_le_Census_ProcessorManufacturerIdentifier
      #    - cce_le_Census_ProcessorModelIdentifier
    - cce_le_Census_ThresholdOptIn
      #    - cce_le_CityIdentifier
    - cce_le_CountryIdentifier
      #    - cce_le_DefaultBrowsersIdentifier
    - cce_le_EngineVersion
    - cce_le_Firewall
    - cce_le_GeoNameIdentifier
    - cce_le_HasTpm
    - cce_le_IeVerIdentifier
    - cce_le_IsBeta
    - cce_le_IsProtected
    - cce_le_IsSxsPassiveMode
    - cce_le_LocaleEnglishNameIdentifier
    - cce_le_MachineIdentifier
    - cce_le_OrganizationIdentifier
    - cce_le_OsBuild
    - cce_le_OsBuildLab
    - cce_le_OsPlatformSubRelease
    - cce_le_OsSuite
      ###    - cce_le_OsVer
    - cce_le_Platform
    - cce_le_Processor
    - cce_le_ProductName
    - cce_le_PuaMode
    - cce_le_RtpStateBitfield
    - cce_le_SkuEdition
    - cce_le_SmartScreen
    - cce_le_SMode
    - cce_le_UacLuaenable
    - cce_le_Wdft_IsGamer
    - cce_le_Wdft_RegionIdentifier
    - fe_le_Census_OEMModelIdentifier
    - fe_le_CityIdentifier
    - fe_le_Census_FirmwareVersionIdentifier
      ###    - fe_le_AvSigVersion
    - fe_le_Census_ProcessorModelIdentifier
    - fe_le_Census_OEMNameIdentifier
    - fe_le_DefaultBrowsersIdentifier
      #    - le_AppVersion
      #    - le_AutoSampleOptIn
      #    - le_AVProductsEnabled
      #    - le_AVProductStatesIdentifier
      #    - le_AvSigVersion
      #    - le_Census_ActivationChannel
      #    - le_Census_ChassisTypeName
      #    - le_Census_DeviceFamily
      #    - le_Census_FirmwareManufacturerIdentifier
      #    - le_Census_FirmwareVersionIdentifier
      #    - le_Census_FlightRing
      #    - le_Census_GenuineStateName
      #    - le_Census_HasOpticalDiskDrive
      #    - le_Census_InternalBatteryType
      #    - le_Census_IsAlwaysOnAlwaysConnectedCapable
      #    - le_Census_IsFlightingInternal
      #    - le_Census_IsFlightsDisabled
      #    - le_Census_IsPenCapable
      #    - le_Census_IsPortableOperatingSystem
      #    - le_Census_IsSecureBootEnabled
      #    - le_Census_IsTouchEnabled
      #    - le_Census_IsVirtualDevice
      #    - le_Census_IsWIMBootEnabled
      #    - le_Census_MDC2FormFactor
      #    - le_Census_OEMModelIdentifier
      #    - le_Census_OEMNameIdentifier
      #    - le_Census_OSArchitecture
      #    - le_Census_OSBranch
      #    - le_Census_OSBuildNumber
      #    - le_Census_OSBuildRevision
      #    - le_Census_OSEdition
      #    - le_Census_OSInstallLanguageIdentifier
      #    - le_Census_OSInstallTypeName
      #    - le_Census_OSSkuName
      #    - le_Census_OSUILocaleIdentifier
      #    - le_Census_OSVersion
      #    - le_Census_OSWUAutoUpdateOptionsName
      #    - le_Census_PowerPlatformRoleName
      #    - le_Census_PrimaryDiskTypeName
      #    - le_Census_ProcessorClass
      #    - le_Census_ProcessorManufacturerIdentifier
      #    - le_Census_ProcessorModelIdentifier
      #    - le_Census_ThresholdOptIn
      #    - le_CityIdentifier
      #    - le_CountryIdentifier
      #    - le_DefaultBrowsersIdentifier
      #    - le_EngineVersion
      #    - le_Firewall
      #    - le_GeoNameIdentifier
      #    - le_HasTpm
      #    - le_IeVerIdentifier
      #    - le_IsBeta
      #    - le_IsProtected
      #    - le_IsSxsPassiveMode
      #    - le_LocaleEnglishNameIdentifier
      #    - le_MachineIdentifier
      #    - le_OrganizationIdentifier
      #    - le_OsBuild
      #    - le_OsBuildLab
      #    - le_OsPlatformSubRelease
      #    - le_OsSuite
      #    - le_OsVer
      #    - le_Platform
      #    - le_Processor
      #    - le_ProductName
      #    - le_PuaMode
      #    - le_RtpStateBitfield
      #    - le_SkuEdition
      #    - le_SmartScreen
      #    - le_SMode
      #    - le_UacLuaenable
      #    - le_Wdft_IsGamer
      #    - le_Wdft_RegionIdentifier
    - e003_MegaPixels
    - e003_Screen_Area
    - e003_aspect_ratio
    - e003_dpi
    - e003_dpi_square
    - e003_new_num_0
    - e003_new_num_1
    - e003_non_primary_drive_MB
    - e003_primary_drive_c_ratio
    - e003_ram_per_processor
    - e003_hghdec_cnt
    - e003_cce_le_AppVersion_1
    - e003_cce_le_AppVersion_2
    - e003_cce_le_AppVersion_3
      ###    - e003_cce_le_AvSigVersion_0
      ###    - e003_cce_le_AvSigVersion_1
    - e003_cce_le_Census_InternalBatteryType
    - e003_cce_le_Census_OSEdition
    - e003_cce_le_Census_OSSkuName
    - e003_cce_le_Census_OSVersion_0
    - e003_cce_le_Census_OSVersion_1
    - e003_cce_le_Census_OSVersion_2
    - e003_cce_le_Census_OSVersion_3
    - e003_cce_le_EngineVersion_2
    - e003_cce_le_EngineVersion_3
    - e003_cce_le_OsBuildLab_0
    - e003_cce_le_OsBuildLab_1
    - e003_cce_le_OsBuildLab_2
    - e003_cce_le_OsBuildLab_3
    - e003_fe_le_monitor_dims
      ###    - e003_fe_le_AvSigVersion_2
    - e005_avsig_ts_diff
    - e005_osver_ts_diff


categorical_features:
    - cce_le_AppVersion
    - cce_le_AutoSampleOptIn
    - cce_le_AVProductsEnabled
    - cce_le_AVProductStatesIdentifier
    - cce_le_AvSigVersion
    - cce_le_Census_ActivationChannel
    - cce_le_Census_ChassisTypeName
    - cce_le_Census_DeviceFamily
    - cce_le_Census_FirmwareManufacturerIdentifier
    - cce_le_Census_FirmwareVersionIdentifier
    - cce_le_Census_FlightRing
    - cce_le_Census_GenuineStateName
    - cce_le_Census_HasOpticalDiskDrive
    - cce_le_Census_InternalBatteryType
    - cce_le_Census_IsAlwaysOnAlwaysConnectedCapable
    - cce_le_Census_IsFlightingInternal
    - cce_le_Census_IsFlightsDisabled
    - cce_le_Census_IsPenCapable
    - cce_le_Census_IsPortableOperatingSystem
    - cce_le_Census_IsSecureBootEnabled
    - cce_le_Census_IsTouchEnabled
    - cce_le_Census_IsVirtualDevice
    - cce_le_Census_IsWIMBootEnabled
    - cce_le_Census_MDC2FormFactor
    - cce_le_Census_OEMModelIdentifier
    - cce_le_Census_OEMNameIdentifier
    - cce_le_Census_OSArchitecture
    - cce_le_Census_OSBranch
    - cce_le_Census_OSBuildNumber
    - cce_le_Census_OSBuildRevision
    - cce_le_Census_OSEdition
    - cce_le_Census_OSInstallLanguageIdentifier
    - cce_le_Census_OSInstallTypeName
    - cce_le_Census_OSSkuName
    - cce_le_Census_OSUILocaleIdentifier
    - cce_le_Census_OSVersion
    - cce_le_Census_OSWUAutoUpdateOptionsName
    - cce_le_Census_PowerPlatformRoleName
    - cce_le_Census_PrimaryDiskTypeName
    - cce_le_Census_ProcessorClass
    - cce_le_Census_ProcessorManufacturerIdentifier
    - cce_le_Census_ProcessorModelIdentifier
    - cce_le_Census_ThresholdOptIn
    - cce_le_CityIdentifier
    - cce_le_CountryIdentifier
    - cce_le_DefaultBrowsersIdentifier
    - cce_le_EngineVersion
    - cce_le_Firewall
    - cce_le_GeoNameIdentifier
    - cce_le_HasTpm
    - cce_le_IeVerIdentifier
    - cce_le_IsBeta
    - cce_le_IsProtected
    - cce_le_IsSxsPassiveMode
    - cce_le_LocaleEnglishNameIdentifier
    - cce_le_MachineIdentifier
    - cce_le_OrganizationIdentifier
    - cce_le_OsBuild
    - cce_le_OsBuildLab
    - cce_le_OsPlatformSubRelease
    - cce_le_OsSuite
    - cce_le_OsVer
    - cce_le_Platform
    - cce_le_Processor
    - cce_le_ProductName
    - cce_le_PuaMode
    - cce_le_RtpStateBitfield
    - cce_le_SkuEdition
    - cce_le_SmartScreen
    - cce_le_SMode
    - cce_le_UacLuaenable
    - cce_le_Wdft_IsGamer
    - cce_le_Wdft_RegionIdentifier
    - e003_cce_le_AppVersion_1
    - e003_cce_le_AppVersion_2
    - e003_cce_le_AppVersion_3
    - e003_cce_le_AvSigVersion_0
    - e003_cce_le_AvSigVersion_1
    - e003_cce_le_Census_InternalBatteryType
    - e003_cce_le_Census_OSEdition
    - e003_cce_le_Census_OSSkuName
    - e003_cce_le_Census_OSVersion_0
    - e003_cce_le_Census_OSVersion_1
    - e003_cce_le_Census_OSVersion_2
    - e003_cce_le_Census_OSVersion_3
    - e003_cce_le_EngineVersion_2
    - e003_cce_le_EngineVersion_3
    - e003_cce_le_OsBuildLab_0
    - e003_cce_le_OsBuildLab_1
    - e003_cce_le_OsBuildLab_2
    - e003_cce_le_OsBuildLab_3
