e000_features: 
    - AppVersion
    - AutoSampleOptIn
    - AVProductsEnabled
      #    - AVProductsInstalled
    - AVProductStatesIdentifier
    - AvSigVersion
    - Census_ActivationChannel
    - Census_ChassisTypeName
    - Census_DeviceFamily
    - Census_FirmwareManufacturerIdentifier
    - Census_FirmwareVersionIdentifier
    - Census_FlightRing
    - Census_GenuineStateName
    - Census_HasOpticalDiskDrive
      #    - Census_InternalBatteryNumberOfCharges
    - Census_InternalBatteryType
      #    - Census_InternalPrimaryDiagonalDisplaySizeInInches
      #    - Census_InternalPrimaryDisplayResolutionHorizontal
      #    - Census_InternalPrimaryDisplayResolutionVertical
    - Census_IsAlwaysOnAlwaysConnectedCapable
    - Census_IsFlightingInternal
    - Census_IsFlightsDisabled
    - Census_IsPenCapable
    - Census_IsPortableOperatingSystem
    - Census_IsSecureBootEnabled
    - Census_IsTouchEnabled
    - Census_IsVirtualDevice
    - Census_IsWIMBootEnabled
    - Census_MDC2FormFactor
    - Census_OEMModelIdentifier
    - Census_OEMNameIdentifier
    - Census_OSArchitecture
    - Census_OSBranch
    - Census_OSBuildNumber
    - Census_OSBuildRevision
    - Census_OSEdition
    - Census_OSInstallLanguageIdentifier
    - Census_OSInstallTypeName
    - Census_OSSkuName
    - Census_OSUILocaleIdentifier
    - Census_OSVersion
    - Census_OSWUAutoUpdateOptionsName
    - Census_PowerPlatformRoleName
      #    - Census_PrimaryDiskTotalCapacity
    - Census_PrimaryDiskTypeName
    - Census_ProcessorClass
      #    - Census_ProcessorCoreCount
    - Census_ProcessorManufacturerIdentifier
    - Census_ProcessorModelIdentifier
      #    - Census_SystemVolumeTotalCapacity
    - Census_ThresholdOptIn
      #    - Census_TotalPhysicalRAM
    - CityIdentifier
    - CountryIdentifier
    - DefaultBrowsersIdentifier
    - EngineVersion
    - Firewall
    - GeoNameIdentifier
    - HasTpm
    - IeVerIdentifier
    - IsBeta
    - IsProtected
    - IsSxsPassiveMode
    - LocaleEnglishNameIdentifier
    - MachineIdentifier
    - OrganizationIdentifier
    - OsBuild
    - OsBuildLab
    - OsPlatformSubRelease
    - OsSuite
    - OsVer
    - Platform
    - Processor
    - ProductName
    - PuaMode
    - RtpStateBitfield
    - SkuEdition
    - SmartScreen
    - SMode
    - UacLuaenable
    - Wdft_IsGamer
    - Wdft_RegionIdentifier


e001_features: 
    - MachineIdentifier
    - le_AppVersion
    - le_AutoSampleOptIn
    - le_AVProductsEnabled
    - le_AVProductStatesIdentifier
    - le_AvSigVersion
    - le_Census_ActivationChannel
    - le_Census_ChassisTypeName
    - le_Census_DeviceFamily
    - le_Census_FirmwareManufacturerIdentifier
    - le_Census_FirmwareVersionIdentifier
    - le_Census_FlightRing
    - le_Census_GenuineStateName
    - le_Census_HasOpticalDiskDrive
    - le_Census_InternalBatteryType
    - le_Census_IsAlwaysOnAlwaysConnectedCapable
    - le_Census_IsFlightingInternal
    - le_Census_IsFlightsDisabled
    - le_Census_IsPenCapable
    - le_Census_IsPortableOperatingSystem
    - le_Census_IsSecureBootEnabled
    - le_Census_IsTouchEnabled
    - le_Census_IsVirtualDevice
    - le_Census_IsWIMBootEnabled
    - le_Census_MDC2FormFactor
    - le_Census_OEMModelIdentifier
    - le_Census_OEMNameIdentifier
    - le_Census_OSArchitecture
    - le_Census_OSBranch
    - le_Census_OSBuildNumber
    - le_Census_OSBuildRevision
    - le_Census_OSEdition
    - le_Census_OSInstallLanguageIdentifier
    - le_Census_OSInstallTypeName
    - le_Census_OSSkuName
    - le_Census_OSUILocaleIdentifier
    - le_Census_OSVersion
    - le_Census_OSWUAutoUpdateOptionsName
    - le_Census_PowerPlatformRoleName
    - le_Census_PrimaryDiskTypeName
    - le_Census_ProcessorClass
    - le_Census_ProcessorManufacturerIdentifier
    - le_Census_ProcessorModelIdentifier
    - le_Census_ThresholdOptIn
    - le_CityIdentifier
    - le_CountryIdentifier
    - le_DefaultBrowsersIdentifier
    - le_EngineVersion
    - le_Firewall
    - le_GeoNameIdentifier
    - le_HasTpm
    - le_IeVerIdentifier
    - le_IsBeta
    - le_IsProtected
    - le_IsSxsPassiveMode
    - le_LocaleEnglishNameIdentifier
    - le_MachineIdentifier
    - le_OrganizationIdentifier
    - le_OsBuild
    - le_OsBuildLab
    - le_OsPlatformSubRelease
    - le_OsSuite
    - le_OsVer
    - le_Platform
    - le_Processor
    - le_ProductName
    - le_PuaMode
    - le_RtpStateBitfield
    - le_SkuEdition
    - le_SmartScreen
    - le_SMode
    - le_UacLuaenable
    - le_Wdft_IsGamer
    - le_Wdft_RegionIdentifier


e002_features: 
    - MachineIdentifier
    - le_AppVersion
    - le_AutoSampleOptIn
    - le_AVProductsEnabled
    - le_AVProductStatesIdentifier
    - le_AvSigVersion
    - le_Census_ActivationChannel
    - le_Census_ChassisTypeName
    - le_Census_DeviceFamily
    - le_Census_FirmwareManufacturerIdentifier
    - le_Census_FirmwareVersionIdentifier
    - le_Census_FlightRing
    - le_Census_GenuineStateName
    - le_Census_HasOpticalDiskDrive
    - le_Census_InternalBatteryType
    - le_Census_IsAlwaysOnAlwaysConnectedCapable
    - le_Census_IsFlightingInternal
    - le_Census_IsFlightsDisabled
    - le_Census_IsPenCapable
    - le_Census_IsPortableOperatingSystem
    - le_Census_IsSecureBootEnabled
    - le_Census_IsTouchEnabled
    - le_Census_IsVirtualDevice
    - le_Census_IsWIMBootEnabled
    - le_Census_MDC2FormFactor
    - le_Census_OEMModelIdentifier
    - le_Census_OEMNameIdentifier
    - le_Census_OSArchitecture
    - le_Census_OSBranch
    - le_Census_OSBuildNumber
    - le_Census_OSBuildRevision
    - le_Census_OSEdition
    - le_Census_OSInstallLanguageIdentifier
    - le_Census_OSInstallTypeName
    - le_Census_OSSkuName
    - le_Census_OSUILocaleIdentifier
    - le_Census_OSVersion
    - le_Census_OSWUAutoUpdateOptionsName
    - le_Census_PowerPlatformRoleName
    - le_Census_PrimaryDiskTypeName
    - le_Census_ProcessorClass
    - le_Census_ProcessorManufacturerIdentifier
    - le_Census_ProcessorModelIdentifier
    - le_Census_ThresholdOptIn
    - le_CityIdentifier
    - le_CountryIdentifier
    - le_DefaultBrowsersIdentifier
    - le_EngineVersion
    - le_Firewall
    - le_GeoNameIdentifier
    - le_HasTpm
    - le_IeVerIdentifier
    - le_IsBeta
    - le_IsProtected
    - le_IsSxsPassiveMode
    - le_LocaleEnglishNameIdentifier
    - le_MachineIdentifier
    - le_OrganizationIdentifier
    - le_OsBuild
    - le_OsBuildLab
    - le_OsPlatformSubRelease
    - le_OsSuite
    - le_OsVer
    - le_Platform
    - le_Processor
    - le_ProductName
    - le_PuaMode
    - le_RtpStateBitfield
    - le_SkuEdition
    - le_SmartScreen
    - le_SMode
    - le_UacLuaenable
    - le_Wdft_IsGamer
    - le_Wdft_RegionIdentifier


e003_features: 
    - MachineIdentifier
    - e003_EngineVersion_1
    - e003_EngineVersion_2
    - e003_EngineVersion_3
    - e003_AppVersion_1
    - e003_AppVersion_2
    - e003_AppVersion_3
    - e003_AvSigVersion_0
    - e003_AvSigVersion_1
    - e003_AvSigVersion_2
    - e003_AvSigVersion_3
    - e003_OsBuildLab_0
    - e003_OsBuildLab_1
    - e003_OsBuildLab_2
    - e003_OsBuildLab_3
    - e003_Census_OSVersion_0
    - e003_Census_OSVersion_1
    - e003_Census_OSVersion_2
    - e003_Census_OSVersion_3
    - e003_monitor_dims
    - e003_Census_InternalBatteryType
    - e003_Census_OSEdition
    - e003_Census_OSSkuName

e003_features: 
    - MachineIdentifier
    - e003_EngineVersion_2
    - e003_EngineVersion_3
    - e003_AppVersion_1
    - e003_AppVersion_2
    - e003_AppVersion_3
    - e003_AvSigVersion_0
    - e003_AvSigVersion_1
    - e003_AvSigVersion_2
    - e003_OsBuildLab_0
    - e003_OsBuildLab_1
    - e003_OsBuildLab_2
    - e003_OsBuildLab_3
    - e003_Census_OSVersion_0
    - e003_Census_OSVersion_1
    - e003_Census_OSVersion_2
    - e003_Census_OSVersion_3
    - e003_monitor_dims
    - e003_Census_InternalBatteryType
    - e003_Census_OSEdition
    - e003_Census_OSSkuName


e003_le_features: 
    - MachineIdentifier
    - e003_le_EngineVersion_2
    - e003_le_EngineVersion_3
    - e003_le_AppVersion_1
    - e003_le_AppVersion_2
    - e003_le_AppVersion_3
    - e003_le_AvSigVersion_0
    - e003_le_AvSigVersion_1
    - e003_le_AvSigVersion_2
    - e003_le_OsBuildLab_0
    - e003_le_OsBuildLab_1
    - e003_le_OsBuildLab_2
    - e003_le_OsBuildLab_3
    - e003_le_Census_OSVersion_0
    - e003_le_Census_OSVersion_1
    - e003_le_Census_OSVersion_2
    - e003_le_Census_OSVersion_3
    - e003_le_monitor_dims
    - e003_le_Census_InternalBatteryType
    - e003_le_Census_OSEdition
    - e003_le_Census_OSSkuName

e009:
    - MachineIdentifier
    - e009_OsVer_0
    - e009_OsVer_1
    - e009_OsVer_2
    - e009_OsVer_3

e009_le:
    - MachineIdentifier
    - e009_le_OsVer_0
    - e009_le_OsVer_1
    - e009_le_OsVer_2
    - e009_le_OsVer_3

e017_le_cce:
    - MachineIdentifier
    - cce_le_AppVersion
    - cce_le_AutoSampleOptIn
    - cce_le_AVProductsEnabled
    - cce_le_AVProductStatesIdentifier
    - cce_le_AvSigVersion
    - cce_le_Census_ActivationChannel
    - cce_le_Census_ChassisTypeName
    - cce_le_Census_DeviceFamily
    - cce_le_Census_FirmwareManufacturerIdentifier
    - cce_le_Census_FirmwareVersionIdentifier
    - cce_le_Census_FlightRing
    - cce_le_Census_GenuineStateName
    - cce_le_Census_HasOpticalDiskDrive
    - cce_le_Census_InternalBatteryType
    - cce_le_Census_IsAlwaysOnAlwaysConnectedCapable
    - cce_le_Census_IsFlightingInternal
    - cce_le_Census_IsFlightsDisabled
    - cce_le_Census_IsPenCapable
    - cce_le_Census_IsPortableOperatingSystem
    - cce_le_Census_IsSecureBootEnabled
    - cce_le_Census_IsTouchEnabled
    - cce_le_Census_IsVirtualDevice
    - cce_le_Census_IsWIMBootEnabled
    - cce_le_Census_MDC2FormFactor
    - cce_le_Census_OEMModelIdentifier
    - cce_le_Census_OEMNameIdentifier
    - cce_le_Census_OSArchitecture
    - cce_le_Census_OSBranch
    - cce_le_Census_OSBuildNumber
    - cce_le_Census_OSBuildRevision
    - cce_le_Census_OSEdition
    - cce_le_Census_OSInstallLanguageIdentifier
    - cce_le_Census_OSInstallTypeName
    - cce_le_Census_OSSkuName
    - cce_le_Census_OSUILocaleIdentifier
    - cce_le_Census_OSVersion
    - cce_le_Census_OSWUAutoUpdateOptionsName
    - cce_le_Census_PowerPlatformRoleName
    - cce_le_Census_PrimaryDiskTypeName
    - cce_le_Census_ProcessorClass
    - cce_le_Census_ProcessorManufacturerIdentifier
    - cce_le_Census_ProcessorModelIdentifier
    - cce_le_Census_ThresholdOptIn
    - cce_le_CityIdentifier
    - cce_le_CountryIdentifier
    - cce_le_DefaultBrowsersIdentifier
    - cce_le_EngineVersion
    - cce_le_Firewall
    - cce_le_GeoNameIdentifier
    - cce_le_HasTpm
    - cce_le_IeVerIdentifier
    - cce_le_IsBeta
    - cce_le_IsProtected
    - cce_le_IsSxsPassiveMode
    - cce_le_LocaleEnglishNameIdentifier
    - cce_le_MachineIdentifier
    - cce_le_OrganizationIdentifier
    - cce_le_OsBuild
    - cce_le_OsBuildLab
    - cce_le_OsPlatformSubRelease
    - cce_le_OsSuite
    - cce_le_OsVer
    - cce_le_Platform
    - cce_le_Processor
    - cce_le_ProductName
    - cce_le_PuaMode
    - cce_le_RtpStateBitfield
    - cce_le_SkuEdition
    - cce_le_SmartScreen
    - cce_le_SMode
    - cce_le_UacLuaenable
    - cce_le_Wdft_IsGamer
    - cce_le_Wdft_RegionIdentifier
    - e003_cce_le_AppVersion_1
    - e003_cce_le_AppVersion_2
    - e003_cce_le_AppVersion_3
    - e003_cce_le_AvSigVersion_0
    - e003_cce_le_AvSigVersion_1
    - e003_cce_le_Census_InternalBatteryType
    - e003_cce_le_Census_OSEdition
    - e003_cce_le_Census_OSSkuName
    - e003_cce_le_Census_OSVersion_0
    - e003_cce_le_Census_OSVersion_1
    - e003_cce_le_Census_OSVersion_2
    - e003_cce_le_Census_OSVersion_3
    - e003_cce_le_EngineVersion_2
    - e003_cce_le_EngineVersion_3
    - e003_cce_le_OsBuildLab_0
    - e003_cce_le_OsBuildLab_1
    - e003_cce_le_OsBuildLab_2
    - e003_cce_le_OsBuildLab_3
    - e007_DateAS_day
    - e007_DateAS_dayofweek
    - e007_DateAS_hour
    - e007_DateAS_month
    - e007_DateAS_quarter
    - e007_DateAS_year
    - e007_DateBL_day
    - e007_DateBL_dayofweek
    - e007_DateBL_hour
    - e007_DateBL_month
    - e007_DateBL_quarter
    - e007_DateBL_year
    - e007_DateOS_day
    - e007_DateOS_dayofweek
    - e007_DateOS_hour
    - e007_DateOS_month
    - e007_DateOS_quarter
    - e007_DateOS_year
