e007:
    - MachineIdentifier
    - DateAS
    - DateOS
    - DateBL

e009:
    - MachineIdentifier
    - OsVer

e010:
    - MachineIdentifier
    - Census_OSBuildNumber
    - e003_EngineVersion_2
    - e003_EngineVersion_3
    - e003_AppVersion_1
    - e003_AppVersion_2
    - e003_AppVersion_3
    - e003_Census_OSVersion_0
    - e003_Census_OSVersion_1
    - e003_Census_OSVersion_2
    - e003_Census_OSVersion_3
    - e003_OsBuildLab_0
    - e003_OsBuildLab_1
    - e009_OsVer_0
    - e009_OsVer_1
    - e009_OsVer_2
    - e009_OsVer_3

e011:
    - MachineIdentifier
    - Census_TotalPhysicalRAM
    - Census_ProcessorCoreCount
    - Census_SystemVolumeTotalCapacity
    - Census_PrimaryDiskTotalCapacity
    - e003_non_primary_drive_MB
    - Census_InternalBatteryNumberOfCharges

e012:
    - MachineIdentifier
    - e003_EngineVersion_2
    - e003_EngineVersion_3
    - e003_AppVersion_1
    - e003_AppVersion_2
    - e003_AppVersion_3
    - e003_Census_OSVersion_0
    - e003_Census_OSVersion_1
    - e003_Census_OSVersion_2
    - e003_Census_OSVersion_3
    - e003_OsBuildLab_0
    - e003_OsBuildLab_1
    - e009_OsVer_0
    - e009_OsVer_1
    - e009_OsVer_2
    - e009_OsVer_3
    - e003_cce_le_EngineVersion_2
    - e003_cce_le_EngineVersion_3
    - e003_cce_le_AppVersion_1
    - e003_cce_le_AppVersion_2
    - e003_cce_le_AppVersion_3
    - e003_cce_le_Census_OSVersion_0
    - e003_cce_le_Census_OSVersion_1
    - e003_cce_le_Census_OSVersion_2
    - e003_cce_le_Census_OSVersion_3
    - e003_cce_le_OsBuildLab_0
    - e003_cce_le_OsBuildLab_1
    - e009_cce_le_OsVer_0
    - e009_cce_le_OsVer_1
    - e009_cce_le_OsVer_2
    - e009_cce_le_OsVer_3

e013:
    - MachineIdentifier
    - DateAS

e015:
    - MachineIdentifier
    - DateAS
    - IsProtected

e020:
    - MachineIdentifier
    - DateAS
    - IsBeta
    - IsSxsPassiveMode
    - HasTpm
    - IsProtected
    - AutoSampleOptIn
    - PuaMode
    - SMode
    - Firewall
    - Census_HasOpticalDiskDrive
    - Census_IsPortableOperatingSystem
    - Census_IsFlightingInternal
    - Census_IsFlightsDisabled
    - Census_ThresholdOptIn
    - Census_IsSecureBootEnabled
    - Census_IsWIMBootEnabled
    - Census_IsVirtualDevice
    - Census_IsTouchEnabled
    - Census_IsPenCapable
    - Census_IsAlwaysOnAlwaysConnectedCapable
    - Wdft_IsGamer
    - HasDetections

e021:
    - MachineIdentifier
    - AvSigVersion
    - Census_OSBranch
    - Census_OSVersion
    - OsBuildLab
    - Census_OSBuildRevision
    - EngineVersion
    - AppVersion

e022:
    - MachineIdentifier
    - DateAS

e026:
    - MachineIdentifier
    - AvSigVersion
    - IsBeta
    - IsSxsPassiveMode
    - HasTpm
    - IsProtected
    - AutoSampleOptIn
    - SMode
    - Firewall
    - Census_HasOpticalDiskDrive
    - Census_IsPortableOperatingSystem
    - Census_IsFlightsDisabled
    - Census_IsSecureBootEnabled
    - Census_IsVirtualDevice
    - Census_IsTouchEnabled
    - Census_IsPenCapable
    - Census_IsAlwaysOnAlwaysConnectedCapable
    - Wdft_IsGamer

e027:
    - MachineIdentifier
    - OsVer
    - IsBeta
    - IsSxsPassiveMode
    - HasTpm
    - IsProtected
    - AutoSampleOptIn
    - SMode
    - Firewall
    - Census_HasOpticalDiskDrive
    - Census_IsPortableOperatingSystem
    - Census_IsFlightsDisabled
    - Census_IsSecureBootEnabled
    - Census_IsVirtualDevice
    - Census_IsTouchEnabled
    - Census_IsPenCapable
    - Census_IsAlwaysOnAlwaysConnectedCapable
    - Wdft_IsGamer

