e000_features: 
    - AppVersion
    - AutoSampleOptIn
    - AVProductsEnabled
      #    - AVProductsInstalled
    - AVProductStatesIdentifier
    - AvSigVersion
    - Census_ActivationChannel
    - Census_ChassisTypeName
    - Census_DeviceFamily
    - Census_FirmwareManufacturerIdentifier
    - Census_FirmwareVersionIdentifier
    - Census_FlightRing
    - Census_GenuineStateName
    - Census_HasOpticalDiskDrive
      #    - Census_InternalBatteryNumberOfCharges
    - Census_InternalBatteryType
      #    - Census_InternalPrimaryDiagonalDisplaySizeInInches
      #    - Census_InternalPrimaryDisplayResolutionHorizontal
      #    - Census_InternalPrimaryDisplayResolutionVertical
    - Census_IsAlwaysOnAlwaysConnectedCapable
    - Census_IsFlightingInternal
    - Census_IsFlightsDisabled
    - Census_IsPenCapable
    - Census_IsPortableOperatingSystem
    - Census_IsSecureBootEnabled
    - Census_IsTouchEnabled
    - Census_IsVirtualDevice
    - Census_IsWIMBootEnabled
    - Census_MDC2FormFactor
    - Census_OEMModelIdentifier
    - Census_OEMNameIdentifier
    - Census_OSArchitecture
    - Census_OSBranch
    - Census_OSBuildNumber
    - Census_OSBuildRevision
    - Census_OSEdition
    - Census_OSInstallLanguageIdentifier
    - Census_OSInstallTypeName
    - Census_OSSkuName
    - Census_OSUILocaleIdentifier
    - Census_OSVersion
    - Census_OSWUAutoUpdateOptionsName
    - Census_PowerPlatformRoleName
      #    - Census_PrimaryDiskTotalCapacity
    - Census_PrimaryDiskTypeName
    - Census_ProcessorClass
      #    - Census_ProcessorCoreCount
    - Census_ProcessorManufacturerIdentifier
    - Census_ProcessorModelIdentifier
      #    - Census_SystemVolumeTotalCapacity
    - Census_ThresholdOptIn
      #    - Census_TotalPhysicalRAM
    - CityIdentifier
    - CountryIdentifier
    - DefaultBrowsersIdentifier
    - EngineVersion
    - Firewall
    - GeoNameIdentifier
    - HasTpm
    - IeVerIdentifier
    - IsBeta
    - IsProtected
    - IsSxsPassiveMode
    - LocaleEnglishNameIdentifier
    - MachineIdentifier
    - OrganizationIdentifier
    - OsBuild
    - OsBuildLab
    - OsPlatformSubRelease
    - OsSuite
    - OsVer
    - Platform
    - Processor
    - ProductName
    - PuaMode
    - RtpStateBitfield
    - SkuEdition
    - SmartScreen
    - SMode
    - UacLuaenable
    - Wdft_IsGamer
    - Wdft_RegionIdentifier
